name: "Deploy"

on:
  push:
    branches:
      - 'main'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # To access the gh-pages branch

      - name: Install devbox
        uses: jetify-com/devbox-install-action@v0.11.0
        with:
          enable-cache: 'true'

      - name: Run checks
        run: devbox run check

      - name: Deploy
        run: |
          git config user.name ${{ github.actor }}
          git config user.email devs@example.com
          devbox run deploy
